import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Cloud, Droplets, MapPin, Moon, RefreshCw, Star, Sun, Wind } from 'lucide-react';
import { getWeather, DEFAULT_LOCATION, type LocationResult, type WeatherPayload, weatherIcon, weatherLabel } from '../services/weather';
import { MapView, type MapOverlay } from '../components/Map';

function formatTemp(value: number) { return `${Math.round(value)}°`; }
function formatTime(value: string, timezone: string) { try { return new Intl.DateTimeFormat('en-US', { timeZone: timezone, hour: 'numeric', minute: '2-digit' }).format(new Date(value)); } catch { return value.slice(11, 16); } }
function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-'); }
function loadLocation(): LocationResult { try { return JSON.parse(localStorage.getItem('whatnext-location') || 'null') || DEFAULT_LOCATION; } catch { return DEFAULT_LOCATION; } }
function Glyph({ code, isDay = true }: { code: number; isDay?: boolean }) { const icon = weatherIcon(code, isDay); const props = { size: 28, strokeWidth: 1.6 }; if (icon === 'sun') return <Sun {...props} />; if (icon === 'moon') return <Moon {...props} />; if (icon === 'rain') return <Droplets {...props} />; if (icon === 'cloud' || icon === 'partly') return <Cloud {...props} />; return <Cloud {...props} />; }
function Header({ title }: { title: string }) { return <header className="site-header"><div className="header-inner"><a className="brand" href="/"><div className="brand-mark"><span /><span /><span /></div><span>WhatNext<span className="brand-dot">.</span>com</span></a><nav className="desktop-nav"><a href="/">Home</a><a className={title === 'Forecast' ? 'active' : ''} href="/forecast">Forecast</a><a className={title === 'Live Layer' ? 'active' : ''} href="/map">Live Layer</a><a className={title === 'Favorites' ? 'active' : ''} href="/favorites">Favorites</a><a className={title === 'Compare' ? 'active' : ''} href="/compare">Compare</a></nav><a className="route-back" href="/"><ArrowLeft size={16} /> Dashboard</a></div></header>; }
function Shell({ title, children }: { title: string; children: React.ReactNode }) { return <div className="app-shell"><Header title={title} /><main className="container page-content route-page"><div className="route-kicker"><span className="live-dot" /> {title} · {loadLocation().name}</div>{children}</main></div>; }
function useRouteWeather() { const [location] = useState(loadLocation); const [weather, setWeather] = useState<WeatherPayload | null>(() => { try { return JSON.parse(localStorage.getItem(`whatnext-cache-${location.id}`) || 'null'); } catch { return null; } }); const [loading, setLoading] = useState(!weather); const [error, setError] = useState(''); const refresh = async () => { setLoading(true); setError(''); try { const data = await getWeather(location); setWeather(data); localStorage.setItem(`whatnext-cache-${location.id}`, JSON.stringify(data)); localStorage.setItem('whatnext-last-updated', String(Date.now())); } catch { setError('Live data is unavailable. Showing cached data when available.'); } finally { setLoading(false); } }; useEffect(() => { refresh(); }, []); return { location, weather, loading, error, refresh }; }

export function ForecastPage() { const { location, weather, loading, error, refresh } = useRouteWeather(); return <Shell title="Forecast"><div className="route-hero"><div><p className="eyebrow">Selected location</p><h1>{location.name} forecast</h1><p>Hourly and daily weather generated from the same active location as the dashboard.</p></div><button className="primary-action" onClick={refresh}><RefreshCw size={16} /> Refresh forecast</button></div>{error && <div className="error-banner">{error}</div>}{loading && !weather ? <div className="skeleton skeleton-wide" /> : weather && <><section className="route-grid">{weather.hourly.slice(0, 12).map((hour, index) => <article className={index === 0 ? 'surface-card route-hour current' : 'surface-card route-hour'} key={hour.time}><small>{index === 0 ? 'Now' : formatTime(hour.time, weather.timezone)}</small><Glyph code={hour.weatherCode} /><strong>{formatTemp(hour.temperature)}</strong><span><Droplets size={12} /> {hour.rainProbability}%</span><em><Wind size={12} /> {Math.round(hour.windSpeed)} km/h</em></article>)}</section><section className="surface-card route-panel"><div className="card-heading"><div><div className="eyebrow">This week</div><h2>7-day outlook</h2></div><MapPin size={18} /></div><div className="week-list">{weather.daily.map((day) => <div className="week-row" key={day.date}><strong>{new Intl.DateTimeFormat('en-US', { weekday: 'short' }).format(new Date(`${day.date}T12:00:00`))}</strong><Glyph code={day.weatherCode} /><span>{weatherLabel(day.weatherCode)}</span><span><Droplets size={13} /> {day.rainProbability}%</span><b>{formatTemp(day.high)} <small>/ {formatTemp(day.low)}</small></b></div>)}</div></section></>}</Shell>; }

export function LiveLayerPage() { const { location, weather, loading } = useRouteWeather(); const [overlay, setOverlay] = useState<MapOverlay>('rain'); const layers: MapOverlay[] = ['rain', 'clouds', 'temperature', 'wind']; return <Shell title="Live Layer"><div className="route-hero"><div><p className="eyebrow">Real map layer</p><h1>Weather around {location.name}</h1><p>Pan, zoom, and switch between supported weather tiles for the active coordinates.</p></div></div>{loading && !weather ? <div className="skeleton skeleton-wide" /> : <section className="surface-card route-map-panel"><div className="map-layer-controls">{layers.map((layer) => <button key={layer} className={overlay === layer ? 'active' : ''} onClick={() => setOverlay(layer)}>{layer[0].toUpperCase() + layer.slice(1)}</button>)}</div><MapView key={`${location.latitude}-${location.longitude}`} overlay={overlay} className="route-map" initialCenter={{ lat: location.latitude, lng: location.longitude }} initialZoom={10} /><p className="map-note"><span className="live-dot" /> {import.meta.env.VITE_WEATHER_API_KEY ? `Live ${overlay} tiles enabled` : 'Add VITE_WEATHER_API_KEY in Vercel to enable OpenWeatherMap weather tiles.'} · {location.latitude.toFixed(3)}, {location.longitude.toFixed(3)}</p></section>}</Shell>; }

export function FavoritesPage() { const [favorites] = useState<LocationResult[]>(() => { try { return JSON.parse(localStorage.getItem('whatnext-favorites') || '[]'); } catch { return []; } }); return <Shell title="Favorites"><div className="route-hero"><div><p className="eyebrow">Your places</p><h1>Favorite locations</h1><p>Open a saved city and every dashboard section will refresh to that location.</p></div></div>{favorites.length ? <div className="route-grid favorites-grid">{favorites.map((item) => <a className="surface-card favorite-route-card" href={`/weather/${slug(item.name)}`} key={item.id}><span className="saved-avatar"><Star size={18} /></span><div><strong>{item.name}</strong><small>{[item.admin1, item.country].filter(Boolean).join(', ')}</small></div><ChevronRight size={18} /></a>)}</div> : <section className="surface-card empty-route"><Star size={24} /><h2>No favorite locations yet</h2><p>Search for a city on the dashboard and save it here.</p><a className="primary-action" href="/">Search weather</a></section>}</Shell>; }

export function ComparePage() { const active = loadLocation(); const favorites: LocationResult[] = (() => { try { return JSON.parse(localStorage.getItem('whatnext-favorites') || '[]'); } catch { return []; } })(); const candidates = [active, ...favorites.filter((item) => item.id !== active.id)].slice(0, 3); const [items, setItems] = useState<Array<{ location: LocationResult; weather: WeatherPayload | null }>>([]); const [loading, setLoading] = useState(true); useEffect(() => { Promise.all(candidates.map(async (location) => { try { return { location, weather: await getWeather(location) }; } catch { return { location, weather: null }; } })).then(setItems).finally(() => setLoading(false)); }, []); return <Shell title="Compare"><div className="route-hero"><div><p className="eyebrow">Side by side</p><h1>Compare weather</h1><p>Compare the active location with saved cities using fresh API responses.</p></div></div>{loading ? <div className="skeleton skeleton-wide" /> : <section className="compare-route-grid">{items.map(({ location, weather }) => <article className="surface-card compare-route-card" key={location.id}><div className="card-heading"><div><div className="eyebrow">{location.source === 'favorite' ? 'Favorite' : 'Active location'}</div><h2>{location.name}</h2></div><MapPin size={16} /></div>{weather ? <div className="compare-metrics"><div><span>Temperature</span><strong>{formatTemp(weather.current.temperature)}</strong></div><div><span>Feels like</span><strong>{formatTemp(weather.current.feelsLike)}</strong></div><div><span>Rain chance</span><strong>{weather.daily[0]?.rainProbability}%</strong></div><div><span>Humidity</span><strong>{weather.current.humidity}%</strong></div><div><span>Wind</span><strong>{Math.round(weather.current.windSpeed)} km/h</strong></div><div><span>UV</span><strong>{Math.round(weather.current.uvIndex)}</strong></div></div> : <p className="muted">Weather data unavailable.</p>}</article>)}</section>}</Shell>; }
